#!/bin/bash
target_branch="staging"
working_tree="/home/your_username/your_project_name"

function deploy_exec() {
	unset $(git rev-parse --local-env-vars)
	
	cd $1

	name="your project name"
	project="$name.wsgi"

	sudo supervisorctl -c /etc/supervisord/supervisord.conf stop $name

	wsgi_num=`ps aux | grep "$project" | wc -l`

	# if test $? -eq "0";then
	#     echo [$project] "has been stopped"
	# fi
	if test "$wsgi_num" -gt "1" ;then
		args=`ps aux | grep -w "$project" | awk '{print $2}'`
		n=1
		for i in $args
		do
		  if [ "$n" -eq "$wsgi_num" ];then
			   # echo "$i has been killed."
			   # echo "ok..."
			   break
		  fi
		  kill -9 $i
		  # if test $? -eq "0";then
		  # 	echo "$i has been killed."
		  # fi
		  ((n++))
		done
	fi

	sudo supervisorctl -c /etc/supervisord/supervisord.conf start $name
	echo "done"
	return 0
}

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ -n "$branch" ] && [ "$target_branch" == "$branch" ]; then
        GIT_WORK_TREE=$working_tree git checkout $target_branch -f
        NOW=$(date +"%Y-%m-%d %H:%M")
        deploy_exec $working_tree
		if test $? -eq "0";then
			echo "   /=============================="
			echo "   | MESSION SUCCEESS"
			echo "   | Target branch: $target_branch"
			# echo "   | Target folder: $working_tree"
			echo "   | Tag time	: $NOW"
			echo "   \=============================="
		else
			echo "   /=============================="
			echo "   | MESSION FAIL"
	        echo "   | Tag time     : $NOW"
			echo "   \=============================="
		fi
    fi
done
